### ISSUE TITLE
Version 2.14.1 Capybara onwards breaks javascript prompts

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/flood-risk-acceptance-tests#88]
This might just be the case for us but if we allow the project to take a version of [Capybara](https://github.com/teamcapybara/capybara) beyond 2.14.0 it seems to break the scenario **Add 3 partners then remove one** in `partnership.feature`.

[Version 2.14.1](https://github.com/teamcapybara/capybara/blob/master/History.md#version-2141) does list the fix _Workaround broken system modals when using selenium with headless Chrome_ so it could be connected to that.

However at the time of spotting this and trying to get it sorted we were trying to validate the environment as part of patching to combat the Spectre/Meltdown vulnerability. Hence we took the decision to revert to a version we know works, and look into the issue at a later date.

**Comment by andrewhick** [comment]
@Cruikshanks is this still an issue? `partnership.feature` has passed every time I've run it recently. It looks like we're currently running Capybara 3.32.2 in the FRAE suite. I suggest we close this unless you think there's something we still need to resolve.

**Comment by Cruikshanks** [comment]
See our awesome QA's comments above!
